# Root directory for storing the project artifacts
artifacts_root: artifacts

# Configuration for data ingestion
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/vbabua/Chicken-Disease-Classification/raw/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion